package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DanhMucLoaiVanBanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiVanBanAllPropertiesEquals(DanhMucLoaiVanBan expected, DanhMucLoaiVanBan actual) {
        assertDanhMucLoaiVanBanAutoGeneratedPropertiesEquals(expected, actual);
        assertDanhMucLoaiVanBanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiVanBanAllUpdatablePropertiesEquals(DanhMucLoaiVanBan expected, DanhMucLoaiVanBan actual) {
        assertDanhMucLoaiVanBanUpdatableFieldsEquals(expected, actual);
        assertDanhMucLoaiVanBanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiVanBanAutoGeneratedPropertiesEquals(DanhMucLoaiVanBan expected, DanhMucLoaiVanBan actual) {
        assertThat(expected)
            .as("Verify DanhMucLoaiVanBan auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiVanBanUpdatableFieldsEquals(DanhMucLoaiVanBan expected, DanhMucLoaiVanBan actual) {
        assertThat(expected)
            .as("Verify DanhMucLoaiVanBan relevant properties")
            .satisfies(e -> assertThat(e.getIdLoaiVb()).as("check idLoaiVb").isEqualTo(actual.getIdLoaiVb()))
            .satisfies(e -> assertThat(e.getDienGiai()).as("check dienGiai").isEqualTo(actual.getDienGiai()))
            .satisfies(e -> assertThat(e.getIdLoaiHopDong()).as("check idLoaiHopDong").isEqualTo(actual.getIdLoaiHopDong()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiVanBanUpdatableRelationshipsEquals(DanhMucLoaiVanBan expected, DanhMucLoaiVanBan actual) {}
}
