package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DanhMucLoaiSoCongChungAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiSoCongChungAllPropertiesEquals(DanhMucLoaiSoCongChung expected, DanhMucLoaiSoCongChung actual) {
        assertDanhMucLoaiSoCongChungAutoGeneratedPropertiesEquals(expected, actual);
        assertDanhMucLoaiSoCongChungAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiSoCongChungAllUpdatablePropertiesEquals(
        DanhMucLoaiSoCongChung expected,
        DanhMucLoaiSoCongChung actual
    ) {
        assertDanhMucLoaiSoCongChungUpdatableFieldsEquals(expected, actual);
        assertDanhMucLoaiSoCongChungUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiSoCongChungAutoGeneratedPropertiesEquals(
        DanhMucLoaiSoCongChung expected,
        DanhMucLoaiSoCongChung actual
    ) {
        assertThat(expected)
            .as("Verify DanhMucLoaiSoCongChung auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiSoCongChungUpdatableFieldsEquals(DanhMucLoaiSoCongChung expected, DanhMucLoaiSoCongChung actual) {
        assertThat(expected)
            .as("Verify DanhMucLoaiSoCongChung relevant properties")
            .satisfies(e -> assertThat(e.getIdLoai()).as("check idLoai").isEqualTo(actual.getIdLoai()))
            .satisfies(e -> assertThat(e.getTenLoai()).as("check tenLoai").isEqualTo(actual.getTenLoai()))
            .satisfies(e -> assertThat(e.getTrangThai()).as("check trangThai").isEqualTo(actual.getTrangThai()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiSoCongChungUpdatableRelationshipsEquals(
        DanhMucLoaiSoCongChung expected,
        DanhMucLoaiSoCongChung actual
    ) {}
}
