package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PhanLoaiHopDongAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhanLoaiHopDongAllPropertiesEquals(PhanLoaiHopDong expected, PhanLoaiHopDong actual) {
        assertPhanLoaiHopDongAutoGeneratedPropertiesEquals(expected, actual);
        assertPhanLoaiHopDongAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhanLoaiHopDongAllUpdatablePropertiesEquals(PhanLoaiHopDong expected, PhanLoaiHopDong actual) {
        assertPhanLoaiHopDongUpdatableFieldsEquals(expected, actual);
        assertPhanLoaiHopDongUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhanLoaiHopDongAutoGeneratedPropertiesEquals(PhanLoaiHopDong expected, PhanLoaiHopDong actual) {
        assertThat(expected)
            .as("Verify PhanLoaiHopDong auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhanLoaiHopDongUpdatableFieldsEquals(PhanLoaiHopDong expected, PhanLoaiHopDong actual) {
        assertThat(expected)
            .as("Verify PhanLoaiHopDong relevant properties")
            .satisfies(e -> assertThat(e.getIdPhanLoaiHopDong()).as("check idPhanLoaiHopDong").isEqualTo(actual.getIdPhanLoaiHopDong()))
            .satisfies(e -> assertThat(e.getDienGiai()).as("check dienGiai").isEqualTo(actual.getDienGiai()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhanLoaiHopDongUpdatableRelationshipsEquals(PhanLoaiHopDong expected, PhanLoaiHopDong actual) {}
}
